// Song database for Nate's GH Hub
// Games: RB (Rock Band), GH2 (Guitar Hero 2), GH3 (Guitar Hero 3), GHWT (Guitar Hero World Tour)

const songs = [
    // ==========================================
    // ROCK BAND (2007) - Main Setlist
    // ==========================================
    { title: "Are You Gonna Be My Girl", artist: "Jet", game: "RB" },
    { title: "Ballroom Blitz", artist: "Sweet", game: "RB" },
    { title: "Black Hole Sun", artist: "Soundgarden", game: "RB" },
    { title: "Blitzkrieg Bop", artist: "Ramones", game: "RB" },
    { title: "Celebrity Skin", artist: "Hole", game: "RB" },
    { title: "Cherub Rock", artist: "The Smashing Pumpkins", game: "RB" },
    { title: "Creep", artist: "Radiohead", game: "RB" },
    { title: "Dani California", artist: "Red Hot Chili Peppers", game: "RB" },
    { title: "Dead on Arrival", artist: "Fall Out Boy", game: "RB" },
    { title: "Detroit Rock City", artist: "KISS", game: "RB" },
    { title: "(Don't Fear) The Reaper", artist: "Blue Oyster Cult", game: "RB" },
    { title: "Electric Version", artist: "The New Pornographers", game: "RB" },
    { title: "Enter Sandman", artist: "Metallica", game: "RB" },
    { title: "Epic", artist: "Faith No More", game: "RB" },
    { title: "Flirtin' with Disaster", artist: "Molly Hatchet", game: "RB" },
    { title: "Foreplay/Long Time", artist: "Boston", game: "RB" },
    { title: "Gimme Shelter", artist: "The Rolling Stones", game: "RB" },
    { title: "Go with the Flow", artist: "Queens of the Stone Age", game: "RB" },
    { title: "Green Grass and High Tides", artist: "The Outlaws", game: "RB" },
    { title: "The Hand That Feeds", artist: "Nine Inch Nails", game: "RB" },
    { title: "Here It Goes Again", artist: "OK Go", game: "RB" },
    { title: "Highway Star", artist: "Deep Purple", game: "RB" },
    { title: "I Think I'm Paranoid", artist: "Garbage", game: "RB" },
    { title: "In Bloom", artist: "Nirvana", game: "RB" },
    { title: "Learn to Fly", artist: "Foo Fighters", game: "RB" },
    { title: "Main Offender", artist: "The Hives", game: "RB" },
    { title: "Maps", artist: "Yeah Yeah Yeahs", game: "RB" },
    { title: "Mississippi Queen", artist: "Mountain", game: "RB" },
    { title: "Next to You", artist: "The Police", game: "RB" },
    { title: "Orange Crush", artist: "R.E.M.", game: "RB" },
    { title: "Paranoid", artist: "Black Sabbath", game: "RB" },
    { title: "Reptilia", artist: "The Strokes", game: "RB" },
    { title: "Run to the Hills", artist: "Iron Maiden", game: "RB" },
    { title: "Sabotage", artist: "Beastie Boys", game: "RB" },
    { title: "Say It Ain't So", artist: "Weezer", game: "RB" },
    { title: "Should I Stay or Should I Go", artist: "The Clash", game: "RB" },
    { title: "Suffragette City", artist: "David Bowie", game: "RB" },
    { title: "Tom Sawyer", artist: "Rush", game: "RB" },
    { title: "Train Kept A Rollin'", artist: "Aerosmith", game: "RB" },
    { title: "Vasoline", artist: "Stone Temple Pilots", game: "RB" },
    { title: "Wanted Dead or Alive", artist: "Bon Jovi", game: "RB" },
    { title: "Wave of Mutilation", artist: "Pixies", game: "RB" },
    { title: "Welcome Home", artist: "Coheed and Cambria", game: "RB" },
    { title: "When You Were Young", artist: "The Killers", game: "RB" },
    { title: "Won't Get Fooled Again", artist: "The Who", game: "RB" },

    // Rock Band - Bonus Tracks
    { title: "29 Fingers", artist: "The Konks", game: "RB" },
    { title: "Blood Doll", artist: "Anarchy Club", game: "RB" },
    { title: "Brainpower", artist: "Freezepop", game: "RB" },
    { title: "Can't Let Go", artist: "Death of the Cool", game: "RB" },
    { title: "Day Late, Dollar Short", artist: "The Acro-Brats", game: "RB" },
    { title: "I Get By", artist: "Honest Bob and the Factory-to-Dealer Incentives", game: "RB" },
    { title: "I'm So Sick", artist: "Flyleaf", game: "RB" },
    { title: "Nightmare", artist: "Crooked X", game: "RB" },
    { title: "Outside", artist: "Tribe", game: "RB" },
    { title: "Pleasure (Pleasure)", artist: "Bang Camaro", game: "RB" },
    { title: "Seven", artist: "Vagiant", game: "RB" },
    { title: "Time We Had", artist: "The Mother Hips", game: "RB" },
    { title: "Timmy and the Lords of the Underworld", artist: "Timmy and the Lords of the Underworld", game: "RB" },

    // ==========================================
    // GUITAR HERO 2 (2006) - Main Career
    // ==========================================
    { title: "Shout at the Devil", artist: "Motley Crue", game: "GH2" },
    { title: "Mother", artist: "Danzig", game: "GH2" },
    { title: "Surrender", artist: "Cheap Trick", game: "GH2" },
    { title: "Woman", artist: "Wolfmother", game: "GH2" },
    { title: "Tonight I'm Gonna Rock You Tonight", artist: "Spinal Tap", game: "GH2" },
    { title: "Strutter", artist: "KISS", game: "GH2" },
    { title: "Heart-Shaped Box", artist: "Nirvana", game: "GH2" },
    { title: "Message in a Bottle", artist: "The Police", game: "GH2" },
    { title: "You Really Got Me", artist: "Van Halen", game: "GH2" },
    { title: "Carry On Wayward Son", artist: "Kansas", game: "GH2" },
    { title: "Monkey Wrench", artist: "Foo Fighters", game: "GH2" },
    { title: "Them Bones", artist: "Alice in Chains", game: "GH2" },
    { title: "Search and Destroy", artist: "Iggy Pop and The Stooges", game: "GH2" },
    { title: "Tattooed Love Boys", artist: "The Pretenders", game: "GH2" },
    { title: "War Pigs", artist: "Black Sabbath", game: "GH2" },
    { title: "Cherry Pie", artist: "Warrant", game: "GH2" },
    { title: "Who Was in My Room Last Night?", artist: "Butthole Surfers", game: "GH2" },
    { title: "Girlfriend", artist: "Matthew Sweet", game: "GH2" },
    { title: "Can't You Hear Me Knocking", artist: "The Rolling Stones", game: "GH2" },
    { title: "Sweet Child O' Mine", artist: "Guns N' Roses", game: "GH2" },
    { title: "Killing in the Name", artist: "Rage Against the Machine", game: "GH2" },
    { title: "John the Fisherman", artist: "Primus", game: "GH2" },
    { title: "Freya", artist: "The Sword", game: "GH2" },
    { title: "Bad Reputation", artist: "Thin Lizzy", game: "GH2" },
    { title: "Last Child", artist: "Aerosmith", game: "GH2" },
    { title: "Crazy on You", artist: "Heart", game: "GH2" },
    { title: "Trippin' on a Hole in a Paper Heart", artist: "Stone Temple Pilots", game: "GH2" },
    { title: "Rock This Town", artist: "Stray Cats", game: "GH2" },
    { title: "Jessica", artist: "The Allman Brothers Band", game: "GH2" },
    { title: "Stop!", artist: "Jane's Addiction", game: "GH2" },
    { title: "Madhouse", artist: "Anthrax", game: "GH2" },
    { title: "Laid to Rest", artist: "Lamb of God", game: "GH2" },
    { title: "Psychobilly Freakout", artist: "Reverend Horton Heat", game: "GH2" },
    { title: "YYZ", artist: "Rush", game: "GH2" },
    { title: "Beast and the Harlot", artist: "Avenged Sevenfold", game: "GH2" },
    { title: "Institutionalized", artist: "Suicidal Tendencies", game: "GH2" },
    { title: "Misirlou", artist: "Dick Dale", game: "GH2" },
    { title: "Hangar 18", artist: "Megadeth", game: "GH2" },
    { title: "Free Bird", artist: "Lynyrd Skynyrd", game: "GH2" },

    // Guitar Hero 2 - Bonus Songs
    { title: "Arterial Black", artist: "Drist", game: "GH2" },
    { title: "Collide", artist: "Anarchy Club", game: "GH2" },
    { title: "Drink Up", artist: "Ounce of Self", game: "GH2" },
    { title: "Fall of Pangea", artist: "Graveyard BBQ", game: "GH2" },
    { title: "FTK", artist: "Vagiant", game: "GH2" },
    { title: "Gemini", artist: "Brian Kahanek", game: "GH2" },
    { title: "Get Ready 2 Rokk", artist: "Freezepop", game: "GH2" },
    { title: "Halo Theme (Mjolnir Mix)", artist: "Martin O'Donnell and Michael Salvatori", game: "GH2" },
    { title: "Jordan", artist: "Buckethead", game: "GH2" },
    { title: "Laughtrack", artist: "The Incredible Moses Leroy", game: "GH2" },
    { title: "Less Talk More Rokk", artist: "Freezepop", game: "GH2" },
    { title: "Life Wasted", artist: "Pearl Jam", game: "GH2" },
    { title: "The Light That Blinds", artist: "Shadows Fall", game: "GH2" },
    { title: "Mr. Fix It", artist: "The Amazing Royal Crowns", game: "GH2" },
    { title: "One for the Road", artist: "Breaking Wheel", game: "GH2" },
    { title: "Parasite", artist: "The Bags", game: "GH2" },
    { title: "Push Push (Lady Lightning)", artist: "Bang Camaro", game: "GH2" },
    { title: "Radium Eyes", artist: "Count Zero", game: "GH2" },
    { title: "Raw Dog", artist: "The Last Vegas", game: "GH2" },
    { title: "Red Lottery", artist: "Megasus", game: "GH2" },
    { title: "Six", artist: "All That Remains", game: "GH2" },
    { title: "Soy Bomb", artist: "Honest Bob and the Factory-to-Dealer Incentives", game: "GH2" },
    { title: "The Trooper", artist: "Iron Maiden", game: "GH2" },
    { title: "Thunderhorse", artist: "Dethklok", game: "GH2" },
    { title: "Trogdor", artist: "Strong Bad", game: "GH2" },
    { title: "X-Stream", artist: "Voivod", game: "GH2" },
    { title: "Yes We Can", artist: "Made in Mexico", game: "GH2" },

    // ==========================================
    // GUITAR HERO 3: LEGENDS OF ROCK (2007)
    // ==========================================
    { title: "Slow Ride", artist: "Foghat", game: "GH3" },
    { title: "Talk Dirty to Me", artist: "Poison", game: "GH3" },
    { title: "Hit Me with Your Best Shot", artist: "Pat Benatar", game: "GH3" },
    { title: "Story of My Life", artist: "Social Distortion", game: "GH3" },
    { title: "Rock and Roll All Nite", artist: "KISS", game: "GH3" },
    { title: "Mississippi Queen", artist: "Mountain", game: "GH3" },
    { title: "School's Out", artist: "Alice Cooper", game: "GH3" },
    { title: "Sunshine of Your Love", artist: "Cream", game: "GH3" },
    { title: "Barracuda", artist: "Heart", game: "GH3" },
    { title: "Bulls on Parade", artist: "Rage Against the Machine", game: "GH3" },
    { title: "When You Were Young", artist: "The Killers", game: "GH3" },
    { title: "Black Magic Woman", artist: "Santana", game: "GH3" },
    { title: "Cherub Rock", artist: "The Smashing Pumpkins", game: "GH3" },
    { title: "The Seeker", artist: "The Who", game: "GH3" },
    { title: "Paint It Black", artist: "The Rolling Stones", game: "GH3" },
    { title: "Paranoid", artist: "Black Sabbath", game: "GH3" },
    { title: "Anarchy in the U.K.", artist: "Sex Pistols", game: "GH3" },
    { title: "Kool Thing", artist: "Sonic Youth", game: "GH3" },
    { title: "My Name Is Jonas", artist: "Weezer", game: "GH3" },
    { title: "Even Flow", artist: "Pearl Jam", game: "GH3" },
    { title: "Holiday in Cambodia", artist: "Dead Kennedys", game: "GH3" },
    { title: "Rock You Like a Hurricane", artist: "Scorpions", game: "GH3" },
    { title: "Same Old Song and Dance", artist: "Aerosmith", game: "GH3" },
    { title: "La Grange", artist: "ZZ Top", game: "GH3" },
    { title: "Welcome to the Jungle", artist: "Guns N' Roses", game: "GH3" },
    { title: "Black Sunshine", artist: "White Zombie", game: "GH3" },
    { title: "The Metal", artist: "Tenacious D", game: "GH3" },
    { title: "Pride and Joy", artist: "Stevie Ray Vaughan", game: "GH3" },
    { title: "Before I Forget", artist: "Slipknot", game: "GH3" },
    { title: "Stricken", artist: "Disturbed", game: "GH3" },
    { title: "3's & 7's", artist: "Queens of the Stone Age", game: "GH3" },
    { title: "Knights of Cydonia", artist: "Muse", game: "GH3" },
    { title: "Cult of Personality", artist: "Living Colour", game: "GH3" },
    { title: "Raining Blood", artist: "Slayer", game: "GH3" },
    { title: "Cliffs of Dover", artist: "Eric Johnson", game: "GH3" },
    { title: "The Number of the Beast", artist: "Iron Maiden", game: "GH3" },
    { title: "One", artist: "Metallica", game: "GH3" },
    { title: "Lay Down", artist: "Priestess", game: "GH3" },
    { title: "Cities on Flame with Rock and Roll", artist: "Blue Oyster Cult", game: "GH3" },
    { title: "Helicopter", artist: "Bloc Party", game: "GH3" },
    { title: "Miss Murder", artist: "AFI", game: "GH3" },
    { title: "Monsters", artist: "Matchbook Romance", game: "GH3" },
    { title: "Reptilia", artist: "The Strokes", game: "GH3" },
    { title: "Sabotage", artist: "Beastie Boys", game: "GH3" },
    { title: "Suck My Kiss", artist: "Red Hot Chili Peppers", game: "GH3" },
    { title: "The Devil Went Down to Georgia", artist: "The Charlie Daniels Band", game: "GH3" },

    // Guitar Hero 3 - Bonus Songs
    { title: "Avalancha", artist: "Heroes del Silencio", game: "GH3" },
    { title: "Can't Be Saved", artist: "Senses Fail", game: "GH3" },
    { title: "Closer", artist: "Lacuna Coil", game: "GH3" },
    { title: "Don't Hold Back", artist: "The Sleeping", game: "GH3" },
    { title: "Down 'n Dirty", artist: "LA Slum Lords", game: "GH3" },
    { title: "F.C.P.R.E.M.I.X.", artist: "The Fall of Troy", game: "GH3" },
    { title: "Generation Rock", artist: "Revolverheld", game: "GH3" },
    { title: "Go That Far", artist: "Bret Michaels Band", game: "GH3" },
    { title: "Hier Kommt Alex", artist: "Die Toten Hosen", game: "GH3" },
    { title: "I'm in the Band", artist: "Camp Freddy", game: "GH3" },
    { title: "Impulse", artist: "An Endless Sporadic", game: "GH3" },
    { title: "In Love", artist: "Scouts of St. Sebastian", game: "GH3" },
    { title: "In the Belly of a Shark", artist: "Gallows", game: "GH3" },
    { title: "Mauvais Garcon", artist: "Naast", game: "GH3" },
    { title: "Metal Heavy Lady", artist: "Lions", game: "GH3" },
    { title: "Minus Celsius", artist: "Backyard Babies", game: "GH3" },
    { title: "My Curse", artist: "Killswitch Engage", game: "GH3" },
    { title: "Nothing for Me Here", artist: "Dope", game: "GH3" },
    { title: "Prayer of the Refugee", artist: "Rise Against", game: "GH3" },
    { title: "Radio Song", artist: "Superbus", game: "GH3" },
    { title: "Ruby", artist: "Kaiser Chiefs", game: "GH3" },
    { title: "She Bangs the Drums", artist: "The Stone Roses", game: "GH3" },
    { title: "Take This Life", artist: "In Flames", game: "GH3" },
    { title: "The Way It Ends", artist: "Prototype", game: "GH3" },
    { title: "Through the Fire and Flames", artist: "DragonForce", game: "GH3" },

    // ==========================================
    // GUITAR HERO WORLD TOUR (2008)
    // ==========================================
    { title: "About a Girl (Unplugged)", artist: "Nirvana", game: "GHWT" },
    { title: "Aggro", artist: "Anouk", game: "GHWT" },
    { title: "American Woman", artist: "The Guess Who", game: "GHWT" },
    { title: "Antisocial", artist: "Trust", game: "GHWT" },
    { title: "Are You Gonna Go My Way", artist: "Lenny Kravitz", game: "GHWT" },
    { title: "Assassin", artist: "Muse", game: "GHWT" },
    { title: "B.Y.O.B.", artist: "System of a Down", game: "GHWT" },
    { title: "Band on the Run", artist: "Wings", game: "GHWT" },
    { title: "Beat It", artist: "Michael Jackson", game: "GHWT" },
    { title: "Beautiful Disaster", artist: "311", game: "GHWT" },
    { title: "Byob", artist: "System of a Down", game: "GHWT" },
    { title: "Come Out and Play", artist: "The Offspring", game: "GHWT" },
    { title: "Crazy Train", artist: "Ozzy Osbourne", game: "GHWT" },
    { title: "Dammit", artist: "Blink-182", game: "GHWT" },
    { title: "Demolition Man", artist: "Sting", game: "GHWT" },
    { title: "Do It Again", artist: "Steely Dan", game: "GHWT" },
    { title: "Escuela de Calor", artist: "Radio Futura", game: "GHWT" },
    { title: "Everlong", artist: "Foo Fighters", game: "GHWT" },
    { title: "Eye of the Tiger", artist: "Survivor", game: "GHWT" },
    { title: "Feel the Pain", artist: "Dinosaur Jr.", game: "GHWT" },
    { title: "Float On", artist: "Modest Mouse", game: "GHWT" },
    { title: "Freak on a Leash", artist: "Korn", game: "GHWT" },
    { title: "Go Your Own Way", artist: "Fleetwood Mac", game: "GHWT" },
    { title: "Good God", artist: "Anouk", game: "GHWT" },
    { title: "Hail to the Freaks", artist: "Beatsteaks", game: "GHWT" },
    { title: "Heartbreaker", artist: "Pat Benatar", game: "GHWT" },
    { title: "Hey Man Nice Shot", artist: "Filter", game: "GHWT" },
    { title: "Hollywood Nights", artist: "Bob Seger", game: "GHWT" },
    { title: "Hot Blooded", artist: "Foreigner", game: "GHWT" },
    { title: "Hot for Teacher", artist: "Van Halen", game: "GHWT" },
    { title: "Hotel California", artist: "Eagles", game: "GHWT" },
    { title: "The Joker", artist: "Steve Miller Band", game: "GHWT" },
    { title: "Kick Out the Jams", artist: "MC5", game: "GHWT" },
    { title: "The Kill", artist: "30 Seconds to Mars", game: "GHWT" },
    { title: "L'Via L'Viaquez", artist: "The Mars Volta", game: "GHWT" },
    { title: "La Bamba", artist: "Los Lobos", game: "GHWT" },
    { title: "Lazy Eye", artist: "Silversun Pickups", game: "GHWT" },
    { title: "Livin' on a Prayer", artist: "Bon Jovi", game: "GHWT" },
    { title: "Love Me Two Times", artist: "The Doors", game: "GHWT" },
    { title: "Love Removal Machine", artist: "The Cult", game: "GHWT" },
    { title: "Love Spreads", artist: "The Stone Roses", game: "GHWT" },
    { title: "Maiden Voyage", artist: "Ted Nugent", game: "GHWT" },
    { title: "The Middle", artist: "Jimmy Eat World", game: "GHWT" },
    { title: "Misery Business", artist: "Paramore", game: "GHWT" },
    { title: "Monsoon", artist: "Tokio Hotel", game: "GHWT" },
    { title: "Mountain Song", artist: "Jane's Addiction", game: "GHWT" },
    { title: "Mr. Crowley", artist: "Ozzy Osbourne", game: "GHWT" },
    { title: "Naked Eye", artist: "The Who", game: "GHWT" },
    { title: "Never Too Late", artist: "The Answer", game: "GHWT" },
    { title: "No Sleep Till Brooklyn", artist: "Beastie Boys", game: "GHWT" },
    { title: "Nuvole e Lenzuola", artist: "Negramaro", game: "GHWT" },
    { title: "Obstacle 1", artist: "Interpol", game: "GHWT" },
    { title: "The One I Love", artist: "R.E.M.", game: "GHWT" },
    { title: "One Armed Scissor", artist: "At the Drive-In", game: "GHWT" },
    { title: "One Way or Another", artist: "Blondie", game: "GHWT" },
    { title: "Our Truth", artist: "Lacuna Coil", game: "GHWT" },
    { title: "Overkill", artist: "Motorhead", game: "GHWT" },
    { title: "Parabola", artist: "Tool", game: "GHWT" },
    { title: "Pretty Vacant", artist: "Sex Pistols", game: "GHWT" },
    { title: "Prisoner of Society", artist: "The Living End", game: "GHWT" },
    { title: "Pull Me Under", artist: "Dream Theater", game: "GHWT" },
    { title: "Purple Haze (Live)", artist: "Jimi Hendrix", game: "GHWT" },
    { title: "Ramblin' Man", artist: "The Allman Brothers Band", game: "GHWT" },
    { title: "Rebel Yell", artist: "Billy Idol", game: "GHWT" },
    { title: "Re-Education (Through Labor)", artist: "Rise Against", game: "GHWT" },
    { title: "Rooftops (A Liberation Broadcast)", artist: "Lostprophets", game: "GHWT" },
    { title: "Santeria", artist: "Sublime", game: "GHWT" },
    { title: "Schism", artist: "Tool", game: "GHWT" },
    { title: "Scream Aim Fire", artist: "Bullet for My Valentine", game: "GHWT" },
    { title: "Shiver", artist: "Coldplay", game: "GHWT" },
    { title: "Some Might Say", artist: "Oasis", game: "GHWT" },
    { title: "Soul Doubt", artist: "No Doubt", game: "GHWT" },
    { title: "Spiderwebs", artist: "No Doubt", game: "GHWT" },
    { title: "Stillborn", artist: "Black Label Society", game: "GHWT" },
    { title: "Stranglehold", artist: "Ted Nugent", game: "GHWT" },
    { title: "Sweet Home Alabama (Live)", artist: "Lynyrd Skynyrd", game: "GHWT" },
    { title: "Satch Boogie", artist: "Joe Satriani", game: "GHWT" },
    { title: "Today", artist: "The Smashing Pumpkins", game: "GHWT" },
    { title: "Too Much Too Young Too Fast", artist: "Airbourne", game: "GHWT" },
    { title: "Toy Boy", artist: "Mika", game: "GHWT" },
    { title: "Trapped Under Ice", artist: "Metallica", game: "GHWT" },
    { title: "Up Around the Bend", artist: "Creedence Clearwater Revival", game: "GHWT" },
    { title: "Vicarious", artist: "Tool", game: "GHWT" },
    { title: "Weapon of Choice", artist: "Black Rebel Motorcycle Club", game: "GHWT" },
    { title: "What I've Done", artist: "Linkin Park", game: "GHWT" },
    { title: "The Wind Cries Mary", artist: "Jimi Hendrix", game: "GHWT" },
    { title: "You're Gonna Say Yeah!", artist: "The Hives", game: "GHWT" },

    // ==========================================
    // GUITAR HERO (2005) - Original Game
    // ==========================================
    // Main Career
    { title: "I Wanna Be Sedated", artist: "Ramones", game: "GH" },
    { title: "Thunder Kiss '65", artist: "White Zombie", game: "GH" },
    { title: "Smoke on the Water", artist: "Deep Purple", game: "GH" },
    { title: "Infected", artist: "Bad Religion", game: "GH" },
    { title: "Iron Man", artist: "Black Sabbath", game: "GH" },
    { title: "More Than a Feeling", artist: "Boston", game: "GH" },
    { title: "You've Got Another Thing Comin'", artist: "Judas Priest", game: "GH" },
    { title: "Take Me Out", artist: "Franz Ferdinand", game: "GH" },
    { title: "Sharp Dressed Man", artist: "ZZ Top", game: "GH" },
    { title: "I Love Rock 'n Roll", artist: "Joan Jett & the Blackhearts", game: "GH" },
    { title: "Stellar", artist: "Incubus", game: "GH" },
    { title: "Heart Full of Black", artist: "Burning Brides", game: "GH" },
    { title: "Symphony of Destruction", artist: "Megadeth", game: "GH" },
    { title: "Killer Queen", artist: "Queen", game: "GH" },
    { title: "Hey You", artist: "The Exies", game: "GH" },
    { title: "Killer Queen", artist: "Queen", game: "GH" },
    { title: "Unsung", artist: "Helmet", game: "GH" },
    { title: "Spanish Castle Magic", artist: "The Jimi Hendrix Experience", game: "GH" },
    { title: "Higher Ground", artist: "Red Hot Chili Peppers", game: "GH" },
    { title: "No One Knows", artist: "Queens of the Stone Age", game: "GH" },
    { title: "Ace of Spades", artist: "Motörhead", game: "GH" },
    { title: "Crossroads", artist: "Cream", game: "GH" },
    { title: "Cochise", artist: "Audioslave", game: "GH" },
    { title: "Take it Off", artist: "The Donnas", game: "GH" },
    { title: "Ziggy Stardust", artist: "David Bowie", game: "GH" },
    { title: "Fat Lip", artist: "Sum 41", game: "GH" },
    { title: "Bark at the Moon", artist: "Ozzy Osbourne", game: "GH" },
    { title: "Texas Flood", artist: "Stevie Ray Vaughan", game: "GH" },
    { title: "Frankenstein", artist: "The Edgar Winter Group", game: "GH" },
    { title: "Cowboys from Hell", artist: "Pantera", game: "GH" },
    { title: "Godzilla", artist: "Blue Öyster Cult", game: "GH" },

    // Guitar Hero - Bonus Songs
    { title: "Cheat on the Church", artist: "Graveyard BBQ", game: "GH" },
    { title: "Cavemen Rejoice", artist: "The Bags", game: "GH" },
    { title: "Eureka, I've Found Love", artist: "The Upper Crust", game: "GH" },
    { title: "Get Ready 2 Rokk", artist: "Freezepop", game: "GH" },
    { title: "Fire it Up", artist: "Black Label Society", game: "GH" },
    { title: "Callout", artist: "The Acro-Brats", game: "GH" },
    { title: "Decontrol", artist: "Drist", game: "GH" },
    { title: "All of This", artist: "Shaimus", game: "GH" },
    { title: "Behind the Mask", artist: "Anarchy Club", game: "GH" },
    { title: "The Breaking Wheel", artist: "Artillery", game: "GH" },
    { title: "Even Rats", artist: "The Slip", game: "GH" },
    { title: "Farewell Myth", artist: "Made in Mexico", game: "GH" },
    { title: "Fly on the Wall", artist: "Din", game: "GH" },
    { title: "Guitar Hero", artist: "Monkey Steals the Peach", game: "GH" },
    { title: "Hey", artist: "Honest Bob and the Factory-to-Dealer Incentives", game: "GH" },
    { title: "Sail Your Ship By", artist: "Count Zero", game: "GH" },
    { title: "Story of My Love", artist: "The Model Sons", game: "GH" },

    // ==========================================
    // ROCK BAND 2 (2008)
    // ==========================================
    { title: "Ace of Spades '08", artist: "Motörhead", game: "RB2" },
    { title: "Alabama Getaway", artist: "The Grateful Dead", game: "RB2" },
    { title: "Alex Chilton", artist: "The Replacements", game: "RB2" },
    { title: "Alive", artist: "Pearl Jam", game: "RB2" },
    { title: "Almost Easy", artist: "Avenged Sevenfold", game: "RB2" },
    { title: "American Woman", artist: "The Guess Who", game: "RB2" },
    { title: "Any Way You Want It", artist: "Journey", game: "RB2" },
    { title: "Aqualung", artist: "Jethro Tull", game: "RB2" },
    { title: "Bad Reputation", artist: "Joan Jett", game: "RB2" },
    { title: "Battery", artist: "Metallica", game: "RB2" },
    { title: "Bodhisattva", artist: "Steely Dan", game: "RB2" },
    { title: "Carry On Wayward Son", artist: "Kansas", game: "RB2" },
    { title: "Chop Suey", artist: "System of a Down", game: "RB2" },
    { title: "Colony of Birchmen", artist: "Mastodon", game: "RB2" },
    { title: "Come Out and Play (Keep 'Em Separated)", artist: "The Offspring", game: "RB2" },
    { title: "Cool for Cats", artist: "Squeeze", game: "RB2" },
    { title: "De-Luxe", artist: "Lush", game: "RB2" },
    { title: "Down with the Sickness", artist: "Disturbed", game: "RB2" },
    { title: "Drain You", artist: "Nirvana", game: "RB2" },
    { title: "E-Pro", artist: "Beck", game: "RB2" },
    { title: "Everlong", artist: "Foo Fighters", game: "RB2" },
    { title: "Eye of the Tiger", artist: "Survivor", game: "RB2" },
    { title: "Feel the Pain", artist: "Dinosaur Jr.", game: "RB2" },
    { title: "Float On", artist: "Modest Mouse", game: "RB2" },
    { title: "Girl's Not Grey", artist: "AFI", game: "RB2" },
    { title: "Give It All", artist: "Rise Against", game: "RB2" },
    { title: "Give It Away", artist: "Red Hot Chili Peppers", game: "RB2" },
    { title: "Go Your Own Way", artist: "Fleetwood Mac", game: "RB2" },
    { title: "Hello There", artist: "Cheap Trick", game: "RB2" },
    { title: "Hungry Like the Wolf", artist: "Duran Duran", game: "RB2" },
    { title: "I Was Wrong", artist: "Social Distortion", game: "RB2" },
    { title: "Kids in America", artist: "The Muffs", game: "RB2" },
    { title: "Lazy Eye", artist: "Silversun Pickups", game: "RB2" },
    { title: "Let There Be Rock", artist: "AC/DC", game: "RB2" },
    { title: "Livin' on a Prayer", artist: "Bon Jovi", game: "RB2" },
    { title: "Lump", artist: "Presidents of the United States of America", game: "RB2" },
    { title: "Man in the Box", artist: "Alice in Chains", game: "RB2" },
    { title: "Master Exploder", artist: "Tenacious D", game: "RB2" },
    { title: "Mountain Song", artist: "Jane's Addiction", game: "RB2" },
    { title: "My Own Worst Enemy", artist: "Lit", game: "RB2" },
    { title: "New Kid in School", artist: "The Donnas", game: "RB2" },
    { title: "Nine in the Afternoon", artist: "Panic! at the Disco", game: "RB2" },
    { title: "One Step Closer", artist: "Linkin Park", game: "RB2" },
    { title: "One Way or Another", artist: "Blondie", game: "RB2" },
    { title: "Our Truth", artist: "Lacuna Coil", game: "RB2" },
    { title: "Painkiller", artist: "Judas Priest", game: "RB2" },
    { title: "Panic Attack", artist: "Dream Theater", game: "RB2" },
    { title: "PDA", artist: "Interpol", game: "RB2" },
    { title: "Peace Sells", artist: "Megadeth", game: "RB2" },
    { title: "Pinball Wizard", artist: "The Who", game: "RB2" },
    { title: "Pretend We're Dead", artist: "L7", game: "RB2" },
    { title: "Psycho Killer", artist: "Talking Heads", game: "RB2" },
    { title: "Pump It Up", artist: "Elvis Costello", game: "RB2" },
    { title: "Ramblin' Man", artist: "The Allman Brothers Band", game: "RB2" },
    { title: "Rebel Girl", artist: "Bikini Kill", game: "RB2" },
    { title: "Rock'n Me", artist: "Steve Miller Band", game: "RB2" },
    { title: "Round and Round", artist: "Ratt", game: "RB2" },
    { title: "Shackler's Revenge", artist: "Guns N' Roses", game: "RB2" },
    { title: "Shooting Star", artist: "Bad Company", game: "RB2" },
    { title: "So What'cha Want", artist: "Beastie Boys", game: "RB2" },
    { title: "Souls of Black", artist: "Testament", game: "RB2" },
    { title: "Spirit in the Sky", artist: "Norman Greenbaum", game: "RB2" },
    { title: "Spoonman", artist: "Soundgarden", game: "RB2" },
    { title: "Tangled Up in Blue", artist: "Bob Dylan", game: "RB2" },
    { title: "Teen Age Riot", artist: "Sonic Youth", game: "RB2" },
    { title: "Testify", artist: "Rage Against the Machine", game: "RB2" },
    { title: "That's What You Get", artist: "Paramore", game: "RB2" },
    { title: "The Middle", artist: "Jimmy Eat World", game: "RB2" },
    { title: "The Trees", artist: "Rush", game: "RB2" },
    { title: "Today", artist: "The Smashing Pumpkins", game: "RB2" },
    { title: "Uncontrollable Urge", artist: "Devo", game: "RB2" },
    { title: "We Got the Beat", artist: "The Go-Go's", game: "RB2" },
    { title: "Where'd You Go?", artist: "The Mighty Mighty Bosstones", game: "RB2" },
    { title: "White Wedding (Part 1)", artist: "Billy Idol", game: "RB2" },
    { title: "You Oughta Know", artist: "Alanis Morissette", game: "RB2" },

    // Rock Band 2 - Free Pack Songs
    { title: "A Jagged Gorgeous Winter", artist: "The Main Drag", game: "RB2" },
    { title: "Conventional Lover", artist: "Speck", game: "RB2" },
    { title: "Get Clean", artist: "Anarchy Club", game: "RB2" },
    { title: "Night Lies", artist: "Bang Camaro", game: "RB2" },
    { title: "Rob the Prez-O-Dent", artist: "That Handsome Devil", game: "RB2" },
    { title: "Shoulder to the Plow", artist: "Breaking Wheel", game: "RB2" },
    { title: "Supreme Girl", artist: "The Sterns", game: "RB2" },
    { title: "Visions", artist: "Abnormality", game: "RB2" },
    { title: "Welcome to the Neighborhood", artist: "Libyans", game: "RB2" }
];
